### ISSUE TITLE
SotiSchema builder fails for complex Freezed class with nested types and Duration fields

### ISSUE THREAD

**Issue by Kaylotrain** [shtse8/spectra#1]
### **Description**

The `SotiSchema` builder fails to generate the schema for a **complex Freezed class** that contains nested types (e.g., lists of objects) and `Duration` fields. However, the builder works correctly with simpler classes without nested objects or special types.

---

### **Steps to Reproduce**

1. **Set up the project:**
   - Add **`soti_schema`, `freezed`, and `json_serializable`** as dependencies.
   - Configure the **`build.yaml`** to ensure the correct builder sequence:

     ```yaml
     targets:
       $default:
         builders:
           json_serializable:
             options:
               explicit_to_json: true

     global_options:
       freezed|freezed:
         runs_before:
           - soti_schema|openApiBuilder
     ```

2. **Define the complex Freezed class:**  
   Use the following code for **ClassPlan**, **Objective**, and **Activity** models:

   ```dart
    import 'package:freezed_annotation/freezed_annotation.dart';
    import 'package:soti_schema/soti_schema.dart';
    
    part 'class_plan.freezed.dart';
    part 'class_plan.g.dart';
    
    @freezed
    @SotiSchema()
    class ClassPlan with _$ClassPlan {
      const factory ClassPlan({
        @JsonKey(name: r'$id') String? id, // ID del documento, // ID del documento
        required String workshopName, // Nombre del taller
        required String group, // Grupo al que pertenece
        required String instructor, // Nombre del instructor
        required DateTime date, // Fecha de la clase
        required String topic, // Tema de la clase
        required Duration duration, // Duración de la clase
        required List<Objective> generalObjectives, // Objetivos generales
        required List<Activity> activities, // Lista de actividades
      }) = _ClassPlan;
    
      factory ClassPlan.fromJson(Map<String, dynamic> json) =>
          _$ClassPlanFromJson(json);
    
      @jsonSchema
      static String get schema => _$ClassPlanSchema;
    }
    
    @freezed
    @SotiSchema()
    class Objective with _$Objective {
      const factory Objective({
        required String description, // Descripción del objetivo
      }) = _Objective;
    
      factory Objective.fromJson(Map<String, dynamic> json) =>
          _$ObjectiveFromJson(json);
    
      @jsonSchema
      static String get schema => _$ObjectiveSchema;
    }
    
    @freezed
    @SotiSchema()
    class Activity with _$Activity {
      const factory Activity({
        required String title, // Título de la actividad
        required String description, // Descripción de la actividad
        required List<String> resources, // Recursos necesarios
        required Duration duration, // Duración de la actividad
      }) = _Activity;
    
      factory Activity.fromJson(Map<String, dynamic> json) =>
          _$ActivityFromJson(json);
    
      @jsonSchema
      static String get schema => _$ActivitySchema;
    }
   ```

3. **Run the build command:**

   ```bash
   dart run build_runner build
   ```

---

### **Observed Behavior**

The following **error is reported** during the build process:

```
[INFO] Generating build script completed, took 560ms
[INFO] Reading cached asset graph completed, took 184ms
[INFO] Checking for updates since last build completed, took 1.5s
[INFO] Running build completed, took 35ms
[INFO] Caching finalized dependency graph completed, took 190ms
[SEVERE] soti_schema:openApiBuilder on lib/models/class_plan.dart (cached):

Unsupported operation: Unsupported data class type. Use @JsonSerializable or @freezed annotation.
[SEVERE] Failed after 244ms
```

---

### **Expected Behavior**

The **`SotiSchema`** builder should generate a valid JSON schema for complex Freezed classes like `ClassPlan`, which contains:
- **Nested lists of objects** (e.g., `List<Objective>`, `List<Activity>`).
- **`Duration` and `DateTime` fields**.
- **JsonKey annotations** with special characters (e.g., `@JsonKey(name: r'$id')`).

---

### **Environment Information**

Below is the complete list of dependencies and versions used in the project. 

#### **Dependencies:**
```yaml
environment:
  sdk: ^3.5.3
  
dependencies:
  flutter:
    sdk: flutter
  appwrite: 12.0.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  openai_dart: ^0.4.2+1
  json_schema: ^5.2.0
  soti_schema: ^1.0.0
```

#### **Dev Dependencies:**
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
```
