### ISSUE TITLE
soti_schema not compatible with the latest version of json_serializable

### ISSUE THREAD

**Issue by csells** [shtse8/spectra#3]
```
[example] dart pub add soti_schema
Because every version of soti_schema depends on source_gen ^1.5.0 and json_serializable >=6.9.1 depends on source_gen ^2.0.0, soti_schema is incompatible with json_serializable >=6.9.1.
So, because example depends on both json_serializable ^6.9.5 and soti_schema any, version solving failed.
exit code 65
```

**Comment by alexobviously** [comment]
Also
```
Because copy_with_extension_gen >=7.0.0 depends on source_gen ^3.0.0 and every version of soti_schema depends on source_gen ^1.5.0, copy_with_extension_gen >=7.0.0 is incompatible with soti_schema.
So, because project depends on both soti_schema any and copy_with_extension_gen ^7.1.0, version solving failed.
```

**Comment by shtse8** [comment]
Fixed in v2.0.0! ✅

Updated all dependencies to be compatible with the latest versions:

```yaml
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
```

The package now works with:
- `json_serializable: ^6.x`
- `freezed: ^2.x`
- Latest Dart 3.x SDK

---

📦 **Package renamed to `spectra_schema`**:
```bash
dart pub add spectra_schema
```

See: https://pub.dev/packages/spectra_schema
